name: Tests
on: [pull_request]

jobs:
  terraform:
    name: Tereraform Validation Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf: [0.12.29, 0.13.4]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ matrix.tf }}
          tf_actions_subcommand: init
          tf_actions_comment: true
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ matrix.tf }}
          tf_actions_subcommand: validate
          tf_actions_comment: true
  docker:
    name: Docker Build test
    runs-on: ubuntu-latest
    steps:
      - name: 'Docker build'
        run: docker build .
